deployment:
 id: "test-deployment"
 description: "some random deployment"
 autoscale_config:
   min_replicas: 0
   max_replicas: 1
   traffic_history_seconds: 100
   scale_down_delay_seconds: 30
   scale_up_delay_seconds: 30
   disable_packing: false
 worker:
   model:
     id: "apparel-clusterering"
     model_version:
       id: "cc911f6b0ed748efb89e3d1359c146c4"
     user_id: "clarifai"
     app_id: "main"
 scheduling_choice: 4
 nodepools:
   - id: "test-nodepool"
     compute_cluster:
         id: "test-compute-cluster"
