deployment:
 id: "test-deployment"
 description: "some random deployment"
 autoscale_config:
   min_replicas: 0
   max_replicas: 1
   traffic_history_seconds: 100
   scale_down_delay_seconds: 30
   scale_up_delay_seconds: 30
   enable_packing: true
 worker:
   model:
     id: "got-ocr-2_0"
     model_version:
       id: "5d92321db5d341b5b4cf407ab34f618f"
     user_id: "stepfun-ai"
     app_id: "ocr"
 scheduling_choice: 4
 nodepools:
   - id: "test-nodepool"
     compute_cluster:
         id: "test-compute-cluster"
