/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 tutorialSidebar: [{type: 'autogenerated', dirName: '.'},
  {
    type: 'category',
    label: 'Additional Resources',
    collapsible: false,
    collapsed: false,
    items: [
  {
    type: 'link',
    label: 'Swagger API Guide',
    href: 'https://api.clarifai.com/api-doc/?url=https://api.clarifai.com/v2/swagger.json',
  },    
  {
      type: 'link',
      label: 'Stack Overflow',
      href: 'https://stackoverflow.com/tags/clarifai/',
  },  
  {
      type: 'link',
      label: 'API Status',
      href: 'https://status.clarifai.com/',
  },
  {
      type: 'link',
      label: 'Clarifai Blog',
      href: 'https://www.clarifai.com/blog/',
  },
  /*
  {
      type: 'link',
      label: 'Clarifai Help',
      href: 'https://help.clarifai.com/',
  },
  */
  {
      type: 'link',
      label: 'Clarifai Community',
      href: 'https://clarifai.com/explore',
  },
  {
    type: 'link',
    label: 'Security Trust Center',
    href: 'https://app.drata.com/trust/9cc5870a-0c38-11ee-865f-029d78a187d9',
  },    
  ],},]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
