build_info:
  python_version: '3.11'
checkpoints:
  hf_token: hf_token
  repo_id: unsloth/Llama-3.2-1B-Instruct
  type: huggingface
  when: runtime
inference_compute_info:
  accelerator_memory: 44Gi
  accelerator_type:
  - NVIDIA-*
  cpu_limit: '1'
  cpu_memory: 13Gi
  num_accelerators: 1
model:
  app_id: your-app-id-here
  id: hf-local-runner-model
  model_type_id: text-to-text
  user_id: your-user-id-here