model:
  id: "my-model-id"
  user_id: "my-user-id"
  app_id: "my-app-id"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: 50m
  cpu_memory: 250Mi
  num_accelerators: 0