model:
  app_id: local-dev-runner-app
  id: local-dev-model
  model_type_id: text-to-text
  user_id: clarifai-user-id

build_info:
  python_version: '3.12'

inference_compute_info:
  cpu_limit: '3'
  cpu_memory: 14Gi
  num_accelerators: 0