build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: 1000m
  cpu_memory: 1Gi
  num_accelerators: 0
model:
  app_id: test-mcp
  id: browser-search-mcp-model
  model_type_id: text-to-text
  user_id: clarifai-user-id